name: wolf_pack
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+7

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil:
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  pinput:
  action_slider: ^0.7.0
  flutter_faq: ^1.0.1+1
  font_awesome_flutter: ^10.7.0
  flutter_rating_bar:
  d_chart: ^2.6.9
  fl_chart:
  dotted_border: ^2.1.0
  percent_indicator: ^4.2.3
  google_maps_flutter: ^2.7.0
  loading_animation_widget: ^1.2.1
  image_picker: ^1.1.2
  zoom_pinch_overlay: ^1.4.3
  shared_preferences: ^2.2.3
  get_storage: ^2.1.1
  flutter_svg:
  qr_flutter:
  mobile_scanner: ^6.0.6
  flutter_launcher_icons: ^0.13.1
  device_preview: ^1.2.0
  flutter_spinkit: ^5.2.1
  fluttertoast:
  flutter_html:
  geocoding:
  gap: ^3.0.1
  carousel_slider: ^5.0.0
  shimmer:
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.4.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications:
  page_transition: ^2.1.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  web_socket_channel: ^3.0.0
  connectivity_plus: ^4.0.1
  socket_io_client:
  open_settings_plus: ^0.4.0
  flutter_google_maps_webservices: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/images/
    - assets/icons/

#flutter_launcher_icons: //////
#  android: true
#  ios: true
#  image_path: "assets/images/spalash.png"
#  min_sdk_android: 21

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
